# Generated by Django 4.2.3 on 2023-07-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='contact')),
            ],
        ),
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('student_number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Nepal', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('tiktok_url', models.URLField()),
                ('image', models.ImageField(upload_to='footer')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='home')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='testimonials')),
            ],
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='visiting')),
            ],
        ),
        migrations.CreateModel(
            name='VisitingName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('ongoing', models.CharField(choices=[('Upcoming', 'Upcoming'), ('We are here', 'We are here'), ('Happening', 'Happening'), ('Wrapped Up', 'Wrapped Up')], default='Upcoming', max_length=200)),
                ('number', models.CharField(choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], default='25', max_length=200)),
                ('visiting_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.visiting')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='project_name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='OperationInCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='eventmanager')),
                ('operationincharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.eventmanagement')),
            ],
        ),
        migrations.CreateModel(
            name='GetTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('designation', models.CharField(blank=True, default='None', max_length=200)),
                ('image', models.ImageField(default='default.png', upload_to='testimonials_student')),
                ('get_testimonials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.testimonials')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='favorite_tools')),
                ('give_number', models.CharField(default='one', max_length=150)),
                ('animation', models.CharField(choices=[('bounceIn', 'bounceIn'), ('fadeInDown', 'fadeInDown'), ('fadeInUp', 'fadeInUp'), ('fadeInRight', 'fadeInRight'), ('fadeInLeft', 'fadeInLeft')], default='bounceIn', max_length=200)),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.myweapon')),
            ],
        ),
        migrations.CreateModel(
            name='BrandingName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.branding')),
            ],
        ),
    ]
